name: Build and Test Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t quote-generator .

    - name: Run container and test it
      run: |
        docker run -d -p 5000:5000 --name test-container quote-generator
        sleep 5
        curl --fail http://localhost:5000/quote
        docker stop test-container


